volumes:
  gradle-cache:
  vscode-extensions:
  vscode-extensions-front:
  cline-cache:
  mcp-server:
  gemini-cache:
  postgres-data:

services:
  apps:
    container_name: actions-sample-app
    build:
      context: ./apps/.devcontainer
    volumes:
      - .:/workspaces:cached
      - gradle-cache:/root/.gradle
      - vscode-extensions-front:/root/.vscode-server/extensions
      - cline-cache:/root/.vscode-server/data/User/globalStorage/saoudrizwan.claude-dev
      - mcp-server:/root/Documents/Cline/MCP
      - gemini-cache:/root/.gemini
    command: sleep infinity
    ports:
      - 8080:8080
  db:
    container_name: actions-sample-postgresqldb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
        - 5432:5432
  
